name: Build iOS App

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    name: Build and Sign iOS App
    runs-on: macos-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
          
      - name: Install Dependencies
        run: |
          xcodebuild -resolvePackageDependencies
          
      - name: Build iOS App
        run: |
          xcodebuild clean archive -project AutoTextIOS/AutoTextIOS.xcodeproj -scheme AutoTextIOS -configuration Release -archivePath build/AutoTextIOS.xcarchive -allowProvisioningUpdates
          
      - name: Create IPA File
        run: |
          xcodebuild -exportArchive -archivePath build/AutoTextIOS.xcarchive -exportPath build -exportOptionsPlist ExportOptions.plist
          
      - name: Upload IPA to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/AutoTextIOS.ipa
          asset_name: AutoTextIOS.ipa
          asset_content_type: application/octet-stream 